name: MaxPlugin
main: MaxKoeth\MaxPlugin\Main
version: 1.0
api: [1.1.0]
load: POSTWORLD
author: Max Koeth
commands:
 chat:
  description: "Send private message: chat <user> <message>"
  usage: "/chat"
  permission: maxplugin.command.generic
 function1:
  description: "Executes function 1"
  usage: "/function1"
  permission: maxplugin.command.generic
 function2:
  description: "Executes function 2"
  usage: "/function2"
  permission: maxplugin.command.generic

permissions:
 maxplugin:
  default: op
  description: "Allows access to all MaxPlugin features."
  children:
   maxplugin.command:
    default: op
    description: "Allows access to all MaxPlugin commands."
    children:
     maxplugin.command.generic:
      default: true
      description: "Allows access to the function1 command."
